[package]
name = "timescale_analytics"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg12"]
pg10 = ["pgx/pg10"]
pg11 = ["pgx/pg11"]
pg12 = ["pgx/pg12"]
pg_test = []

[dependencies]
pgx = "0.1.5"
pgx-macros = "0.1.5"
tdigest = {version = "0.2", features = ["use_serde"]}
bincode = "1.3.1"
serde = "1.0"

[dev-dependencies]
pgx-tests = "0.0.15"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
