[package]
name = "hyperloglog"
version = "0.1.0"
authors = ["Joshua Lockerman <josh@timescale.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dependencies.bytecount]
version = "0.6"
features = ["runtime-dispatch-simd"]
